### ISSUE TITLE
Application shows UTC time instead of current Timezone

### ISSUE THREAD

**Issue by exxa-tech** [Australian-Imaging-Service/charts#11]
When doing testing for Microk8s XNAT application the time is specified in UTC rather than the local timezone. This is undesirable for production environments.
Suggest changing this to local Timezone and then adding section to the Documentation to specify where to add the correct timezone for you location in the Helm template.

**Comment by vs49688** [comment]
@exxa-tech @dean-taylor Can I close this? I see the timezone is being set by cloud-init, and Java should pick this up automatically.
