### ISSUE TITLE
disable both openid and ldap auth methods creates invalid secret.yaml

### ISSUE THREAD

**Issue by dean-taylor** [Australian-Imaging-Service/charts#13]
Logic is required to add an empty auth secret when all auth plugins are disabled

**Comment by vs49688** [comment]
Fixed as of https://github.com/Australian-Imaging-Service/xnat-openid-auth-plugin/releases/tag/1.0.2, will close this is updated.

**Comment by vs49688** [comment]
Fixed as of b5b2e0f4c32a5785febc90739699d9f44445bc56
