### ISSUE TITLE
S3 side container

### ISSUE THREAD

**Issue by dean-taylor** [Australian-Imaging-Service/charts#15]
Enable the use of S3 storage for XNAT and CTP.
An S3 side container has been created and is currently under further development. Zane has highlighted that the current container may have issue if the network mount becomes disconnected. Appropriate recovery is needed, this may be with the use of a local cache, and discovery if the S3FS code initiated a reconnect process.
There is also a requirement to monitor the cache and initiate a flush process if required.

**Comment by vs49688** [comment]
Pull request pending review: https://github.com/Australian-Imaging-Service/s3fs-build/pull/1

**Comment by vs49688** [comment]
Closed after merge of https://github.com/Australian-Imaging-Service/s3fs-build/pull/1
