### ISSUE TITLE
OpenId authentication default values

### ISSUE THREAD

**Issue by dean-taylor** [Australian-Imaging-Service/charts#20]
Modify the OpenId authenticator provider values to:
1. provide default values for all deployments, this would include most of the OpenId values other than the unique identifiers and keys per deployment.
2. create Helm template logic to provide the default if an YAML override value has not been set.
3. Alter the existing secret to reference the template generated value instead of directly form the values file.
This will allow a cleaner deployment values file, allow for common values per configured auth provider for consistency.

**Comment by vs49688** [comment]
Closed in #24
