### ISSUE TITLE
NVIDIA Clara deployment / integration

### ISSUE THREAD

**Issue by dean-taylor** [Australian-Imaging-Service/charts#22]
Incorporate Clara as part of the AIS deployment
* [NVIDIA Clara documentation](https://docs.nvidia.com/clara/)

**Comment by RyanPSullivan7** [comment]
Option 1: Deploy limited CLARA-TRAIN XNAT containers. I don't think this would require changes to helm as it runs atop of XNAT container service. It is stuck on CLARA v3 however. This works as an XNAT PUSH

Option 2: Deploy full CLARA v4 with MONAI. This works as CLARA PULL.
