### ISSUE TITLE
xnat: Default deployment fails with "FATAL: password authentication failed for user "xnat""

### ISSUE THREAD

**Issue by vs49688** [Australian-Imaging-Service/charts#23]
When using the default `values.yaml`, the `postgresql.postgresqlPassword`  value seems to not be applied to the subchart.
Confirmed by looking at the password in the dashboard - it is a default auto-generated value, not the one specified.

**Comment by dean-taylor** [comment]
Documentation should show that the global.postgresql.postgresqlPassword is a requirement
This setting synchronises the xnat and postgresql deployments authentication.  Linked to ISSUE "xnat-web error handling #8".
However this would need to be checked within the xnat umbrella (parent) chart.

**Comment by vs49688** [comment]
Closing, dup of #2
