### ISSUE TITLE
Can't redirect EKS ALB from HTTP to HTTPS

### ISSUE THREAD

**Issue by exxa-tech** [Australian-Imaging-Service/charts#29]
Have got all other annotations working apart from redirection service from HTTP to HTTPS.
It is added but does not redirect. Suspect something in the templates file.

**Comment by exxa-tech** [comment]
I got it to work!
In the values.yaml top level:

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      **alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'**
      alb.ingress.kubernetes.io/healthcheck-path: "/"
      alb.ingress.kubernetes.io/success-codes: "302"
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-southeast-2:XXXXXXXXXX:certificate/XXXXXXXX"
      alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-Ext-2018-06"
  hosts:
    - host: "xnat.exxa.tech"
      paths: [ "/*” ]

In charts/xnat-web/templates/ingress.yaml:

{{- if .Values.ingress.enabled -}}
{{- $fullName := include "xnat-web.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare "<1.14" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: extensions/v1beta1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "xnat-web.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    **- host: "xnat.exxa.tech"
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: xnat-xnat-web
              servicePort: 80**
  {{- end }}

Hardcoding stuff into templates is not best practice but it works.

**Comment by fxusyd** [comment]
Yes, putting them in values file should work as these are injected into the template by the template engine. 
I reckon the goal is to simplify the values file and let the logic kicks in to render the complete manifest. So, the chart has relatively small values file and relatively big template with the logic in it.

**Comment by exxa-tech** [comment]
@fxusyd - I have updated a bit - new ingress.yaml:

{{- if .Values.ingress.enabled -}}
{{- $fullName := include "xnat-web.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $host := .Values.ingress.hosts -}}
{{- if semverCompare "<1.14" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: extensions/v1beta1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "xnat-web.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: "/*"
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: "/*"
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
  {{- end }}

This works. Still not completely picked up from values file but getting better.

**Comment by fxusyd** [comment]
I've made some changes in custom values file and template, so it should be fully working for both of microk8s and eks. support for other environment can be added accordingly. will push the code after some more changes . For now, please give it a try. 

* relevant section in custom values yaml
  # specify k8s environment, e.g. micro8s, aws, openstack...
  environment: openstack
  ingress:
    enabled: true
    annotations:
      microk8s:
        kubernetes.io/ingress.class: "nginx"
        #nginx.ingress.kubernetes.io/whitelist-source-range: "130.95.0.0/16 127.0.0.0/8"
      aws:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/subnets: subnet-0ca0ff609b04ee2b6,subnet-08fc5293a45897e7a,subnet-04a263a1dc7ed2e52
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443},{"HTTP": 80}]'
        alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-2:078690265916:certificate/73292fa0-a775-49d8-9bb3-de5dd09a40a8
        alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
        alb.ingress.kubernetes.io/healthcheck-path: "/"
        alb.ingress.kubernetes.io/success-codes: "302"
        alb.ingress.kubernetes.io/tags: Project=AIS
      openstack:
        # TODO
        kubernetes.io/ingress.class: "xxxx"
      common:
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
        nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "150"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "100"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "100"
    hosts:
      # first domain name is the main one that should used by openid
      - "xnat.microk8s.local"

* ingress.yaml
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "xnat-web.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare "<1.14" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: extensions/v1beta1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "xnat-web.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- range $env, $a := . }}
      {{- if eq $env $.Values.environment }}
        {{- toYaml $a | nindent 4 }}
      {{- end }}
    {{- end }} 
    {{- toYaml .common | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- if eq $.Values.environment "aws" }}
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          {{- else if eq $.Values.environment "openstack" }}
          {{- end }}
          - path: /*
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
    {{- end }}
  {{- end }}

**Comment by exxa-tech** [comment]
I get:
Error: Ingress.extensions "xnat-xnat-web" is invalid: spec: Invalid value: []networking.IngressRule(nil): either `backend` or `rules` must be specified
Does this work for you?

**Comment by fxusyd** [comment]
@exxa-tech  Yes, it works for me. What is your related section in custom values file?

**Comment by exxa-tech** [comment]
I'll have to get back to you on that one - will need to dedicate some time elsewhere for the next few days.

**Comment by fxusyd** [comment]
@exxa-tech I've pushed all AWS change in branch #28, it should work with both of AWS and Microk8s with different custom values files/options. AWS resources pre-provisioned are EFS (access points for archive and prearchive), RDS (Postgresql). As our AWS environments may be different, let's have a quick discussion before you test it.

**Comment by exxa-tech** [comment]
I think this is resolved now (as long as you have 1.18 or before).
I documented.
