### ISSUE TITLE
Maintaining the OpenID plugin

### ISSUE THREAD

**Issue by vs49688** [Australian-Imaging-Service/charts#30]
Basically we need to determine:
* which is the correct upstream repository,
* are we going to update it to XNAT 1.8.x,
* and if so, how long are going to support this?

Triggered by https://github.com/Australian-Imaging-Service/xnat-openid-auth-plugin/issues/2

**Comment by vs49688** [comment]
@dean-taylor fyi https://bitbucket.org/xnatx/openid-auth-plugin/pull-requests/1

**Comment by dean-taylor** [comment]
Currently maintaining the openid plugin with ais repo until upstream has rectified issues or merged ais team changes.
