### ISSUE TITLE
Kustomize as Helm post renderer OR Helm as Kustomize chart inflator plugin?

### ISSUE THREAD

**Issue by dean-taylor** [Australian-Imaging-Service/charts#38]
Team discussion on Kustomize work practice integration.
What do we recommend / support
1. Primarily using Helm and integrating Kustomize as a --post-renderer
2. Primarily using Kustomize and utilising the Helm charts via a chart inflator extension plugin
3. Both
4. Neither, only support Helm charts and leave this up to each deployment to decide

**Comment by dean-taylor** [comment]
Kustomize as Helm post renderer wrapper script (https://raw.githubusercontent.com/dean-taylor/ansible-role-k8s-admin/main/files/kustomize-wrapper.sh)[https://raw.githubusercontent.com/dean-taylor/ansible-role-k8s-admin/main/files/kustomize-wrapper.sh]

**Comment by exxa-tech** [comment]
As I never used kustomize until recently and googled around until I found something that works I don't think I should necessarily need to make a decision here.
Personally I use --post-renderer and it works fine - kustomize is great and essential to use if you want to use the Helm chart, change certain repo templates AND allow for updates without downloading the repo and editing all the files.
I have no idea what a chart inflator extension plugin is so can't comment.

**Comment by dean-taylor** [comment]
Team decision to utilise Helm as the primary deployment mechanism. Kustomizations are added using a post renderer.
