### ISSUE TITLE
[STORY] xnat 1.8.4 update

### ISSUE THREAD

**Issue by dean-taylor** [Australian-Imaging-Service/charts#74]
### Is your feature request related to a problem? Please describe.

XNAT 1.8.4 Has Been Released

### Describe the solution you'd like

XNAT 1.8.4 Has Been Released

### Describe alternatives you've considered

XNAT 1.8.4 Has Been Released

**Comment by fxusyd** [comment]
container image: ghcr.io/australian-imaging-service/xnat-web:1.8.4.1
