### ISSUE TITLE
Helm chart repo replaced by github pages?

### ISSUE THREAD

**Issue by Oblynx** [Australian-Imaging-Service/charts#89]
### Describe the bug

The Helm chart repo doesn't exist any longer; instead, an empty github page is in its place.

### Steps to reproduce

After adding the Helm chart repo:
```
$ helm repo update
...Unable to get an update from the "ais" chart repository (https://australian-imaging-service.github.io/charts):
	failed to fetch https://australian-imaging-service.github.io/charts/index.yaml : 404 Not Found
```

### Expected behavior

the repo should exist

### XNAT Chart Version

1.1.3

**Comment by fxusyd** [comment]
helm repo is restored
